export const mockMovies = [
  {
    id: 634649,
    title: "Spider-Man: No Way Home",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker's life and reputation are turned upside down when his identity is revealed. He turns to Doctor Strange for help, but the spell goes horribly wrong.",
    release_date: "2021-12-15",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    popularity: 5000.123,
    vote_average: 8.2,
    vote_count: 12000,
    genre_ids: [28, 12, 878],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 675353,
    title: "Sonic the Hedgehog 2",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero.",
    release_date: "2022-04-08",
    poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
    popularity: 2800.88,
    vote_average: 7.5,
    vote_count: 4500,
    genre_ids: [28, 35, 10751, 878],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 497698,
    title: "Black Widow",
    original_title: "Black Widow",
    overview:
      "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
    release_date: "2021-07-07",
    poster_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    backdrop_path: "/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg",
    popularity: 3200.75,
    vote_average: 7.1,
    vote_count: 8900,
    genre_ids: [28, 12, 53, 878],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll. He has burned through eight of his nine lives, leaving him with just one last life.",
    release_date: "2022-12-07",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    backdrop_path: "/r9PkFnRUIthgBp2JZZzD380MWZy.jpg",
    popularity: 2900.43,
    vote_average: 8.4,
    vote_count: 6400,
    genre_ids: [16, 12, 35, 10751],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 76600,
    title: "Avatar: The Way of Water",
    original_title: "Avatar: The Way of Water",
    overview:
      "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora.",
    release_date: "2022-12-14",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    popularity: 4600.2,
    vote_average: 7.7,
    vote_count: 9800,
    genre_ids: [28, 12, 878],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 634528,
    title: "The Batman",
    original_title: "The Batman",
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing the serial killer Riddler.",
    release_date: "2022-03-01",
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop_path: "/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    popularity: 3800.65,
    vote_average: 7.8,
    vote_count: 9500,
    genre_ids: [80, 9648, 53],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 572802,
    title: "Aquaman and the Lost Kingdom",
    original_title: "Aquaman and the Lost Kingdom",
    overview:
      "Having failed to defeat Aquaman the first time, Black Manta wields the power of the mythic Black Trident to unleash an ancient and malevolent force.",
    release_date: "2023-12-20",
    poster_path: "/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
    backdrop_path: "/sR0SpCrXamlIkYMdfz83sFn5JS6.jpg",
    popularity: 2100.75,
    vote_average: 6.8,
    vote_count: 4300,
    genre_ids: [28, 12, 14],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 934433,
    title: "Sisu",
    original_title: "Sisu",
    overview:
      "When an ex-soldier who discovers gold in the Lapland wilderness tries to take the loot into the city, Nazi soldiers led by a brutal SS officer battle him.",
    release_date: "2023-01-27",
    poster_path: "/ygO9lowFMXWymATCrhoQXd6gCEh.jpg",
    backdrop_path: "/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
    popularity: 1600.22,
    vote_average: 7.6,
    vote_count: 2100,
    genre_ids: [28, 53, 10752],
    original_language: "fi",
    adult: false,
    video: false,
  },
  {
    id: 615656,
    title: "Meg 2: The Trench",
    original_title: "Meg 2: The Trench",
    overview:
      "A research team encounters multiple threats while exploring the depths of the ocean, including a malevolent mining operation.",
    release_date: "2023-08-02",
    poster_path: "/FQHtuf2zc8suMFE28RyvFt3FJN.jpg",
    backdrop_path: "/qW4crfED8mpNDadSmMdi7ZDzhXF.jpg",
    popularity: 2400.89,
    vote_average: 6.4,
    vote_count: 5000,
    genre_ids: [28, 878, 27],
    original_language: "en",
    adult: false,
    video: false,
  },
  {
    id: 603692,
    title: "John Wick: Chapter 4",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face a new enemy.",
    release_date: "2023-03-22",
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    backdrop_path: "/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
    popularity: 3500.11,
    vote_average: 8.1,
    vote_count: 7800,
    genre_ids: [28, 53, 80],
    original_language: "en",
    adult: false,
    video: false,
  },
];